### ISSUE TITLE
The Big Todo List

### ISSUE THREAD

**Issue by stefanzweifel** [stefanzweifel/user-agent-analyzer#2]
This is my big todo list for the first shippable version of this project:

## Must:

- [x] Purge expired processes
- [x] Cache everything (with Redis)
- [x] Add Screenshots
- [x] Add Error Pages
- [x] Add Better Error Handling (and logging)
- [x] Display a Success Message after starting the process
- [x] Add About / ToS Page, which describes how we process and store your data

## Nice to have:

- [x] Add a legend to the Chart
